api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    version: '0.1.0'

    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'

    swagger:
        api_keys:
            - { name: 'Authorization', type: 'header' }
    formats:
        jsonld:  ['application/ld+json']
        jsonhal: ['application/hal+json']
        xml:     ['application/xml', 'text/xml']
        json:    ['application/json']
        yaml:    ['application/x-yaml']
        csv:     ['text/csv']
        html:    ['text/html']
